# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  secret_scan: eddiewebb/secret_scan@0.0.3
  my_secret_scan:
    orbs:
      node: circleci/python@1.2.1
    commands:
      my_command:
        steps:
          - run: echo "Hellooo"
    jobs:
      my_job:
        executor: node/default
        steps:
          - checkout
          - my_command
          - store_test_results:
            path: test-results
        
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - my_secret_scan/scan
